version: '3'
services:

# Database Service Creation (Mysql)
  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
    volumes:
      - /home/mysql/data
    networks:
      - db-network
      
      
 # App backend service creation
  backend:
    depends_on:
      - database
    container_name: spring_container
    image: milqshake/achat:189
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://database:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    volumes:
      - /home/m2
    stdin_open: true
    tty: true
    networks:
      - backend-network
    restart: on-failure
  
networks:
  backend:
  
#App frontend service creation  
   front:
    build:
      context: .
    container_name: angular
    image: milqshake/angular:frontend
    ports:
      - "8888:80"
    networks:
      - front-network
